src/Entity/AbstractLinkableEntity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\MappedSuperclass;

/** @MappedSuperclass */
abstract class AbstractLinkableEntity {
  /**
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=100)
   */
  private $name;

  /**
   * @ORM\Column(type="string", length=100)
   */
  protected $linkName;

  /**
   * @ORM\Column(type="string", length=8, unique=true)
   */
  protected $linkId;

  public function getId() {
    return $this->id;
  }

  public function setName($newName) {
    $this->name = ucfirst($newName);
    $replace = [ 'ě' => 'e', 'š' => 's', 'č' => 'c', 'ř' => 'r', 'ž' => 'z',
                 'ý' => 'y', 'á' => 'a', 'í' => 'i', 'é' => 'e', 'ú' => 'u',
                 'ů' => 'u', 'ď' => 'd', 'ť' => 't', 'ň' => 'n', 'ó' => 'o',
                 'Ě' => 'E', 'Š' => 'S', 'Č' => 'C', 'Ř' => 'R', 'Ž' => 'Z',
                 'Ý' => 'Y', 'Á' => 'A', 'Í' => 'I', 'É' => 'E', 'Ú' => 'U',
                 'Ů' => 'U', 'Ď' => 'D', 'Ť' => 'T', 'Ň' => 'N', 'Ó' => 'O' ];
    $changed = str_replace(',', '', strtolower(str_replace(array_keys($replace), $replace, $newName)));
    $replaced = preg_replace("/[^A-Za-z ]/", '', $changed);
    $this->linkName = str_replace(' ', '-', strtolower(trim($replaced)));
  }

  protected function generateLinks() {
    $this->linkId = substr(md5(uniqid(mt_rand(), true)), 0,8);
  }

  public function getName() {
    return $this->name;
  }

  public function getLink() {
    return $this->linkName;
  }

  public function getPageId() {
    return $this->linkId;
  }

  /** Returns the rest of the URL, but the first part has to be added in concrete entity.
   * (eg in Board: 'b/'.parent::getUrl();)
   */
  protected function getUrl() {
    return $this->linkId."/".$this->linkName;
  }
}

src/Entity/Deadline.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DeadlineRepository")
 * @ORM\Table(name="deadline")
 */
class Deadline {
  /**
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @var string $text
   * @ORM\Column(type="string", length=256)
   */
  private $text;

  /**
   * @var DateTime $start
   * @ORM\Column(type="date")
   */
  private $start;

  /**
   * @var DateTime $end
   * @ORM\Column(type="date")
   */
  private $end;

  /**
   * @var Issue $issue
   * @ORM\ManyToOne(targetEntity="Issue")
   * @ORM\JoinColumn(name="id_issue", referencedColumnName="id")
   */
  private $issue;

  /**
   * @var Gauge $gauge
   * @ORM\ManyToOne(targetEntity="Gauge")
   * @ORM\JoinColumn(name="id_gauge", referencedColumnName="id", nullable=true, onDelete="CASCADE")
   */
  private $gauge;

  /** @param DateTime $start */
  public function setStart($start) {
    $this->start = $start;
  }

  /** @param string $text */
  public function setText($text) {
    $this->text = $text;
  }

  /** @param DateTime $end */
  public function setEnd($end) {
    $this->end = $end;
  }

  /** @param Issue $issue */
  public function setIssue($issue) {
    $this->issue = $issue;
  }

  /** @param Gauge $gauge */
  public function setGauge($gauge) {
    $this->gauge = $gauge;
  }

  public function getId() {
    return $this->id;
  }

  public function getText() {
    return $this->text;
  }

  public function getStart() {
    return $this->start->format('d. m.');
  }

  public function getStartPicker() {
    return $this->start->format('d/m/Y');
  }

  public function getEnd() {
    return $this->end->format('d. m.');
  }

  public function getEndPicker() {
    return $this->end->format('d/m/Y');
  }

  public function getColor() {
    if($this->gauge === null || $this->gauge->getColor() === null)
      return '#666';
    else
      return $this->gauge->getColor();
  }

  public function getName() {
    if($this->gauge === null)
      return $this->issue->getName();
    else
      return $this->gauge->getName();
  }

  public function getGaugeId() {
    if($this->gauge !== null)
      return $this->gauge->getId();
    else return 'issue';
  }

  public function getGaugeOwner() {
    if($this->gauge !== null)
      return $this->gauge->getBindUserName();
    else return '';
  }

  /** @return Gauge */
  public function getGauge() {
    return $this->gauge;
  }

  public function getDaysLeft() {
    return ((new DateTime("now - 1 day"))->diff($this->end))->format('%a');
  }

  public function getPercentage() {
    $total = $this->start->diff($this->end)->format('%a');
    $now = (new DateTime("now - 1 day"))->diff($this->end)->format('%a');
    if($total == 0) return 100;
    return 100-(($now*100)/$total);
  }

  public function getDuration() {
    return (($this->start)->diff($this->end))->format('%a');
  }

  /** @return Issue */
  public function getIssue() {
    return $this->issue;
  }

}

src/Entity/GaugeChanges.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GaugeChangesRepository")
 * @ORM\Table(name="gauge_changes")
 */
class GaugeChanges {
  /**
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\ManyToOne(targetEntity="Gauge", inversedBy="changes", cascade={"remove"})
   * @ORM\JoinColumn(name="id_gauge", referencedColumnName="id", nullable=true, onDelete="SET NULL")
   */
  private $gauge;

  /**
   * @ORM\Column(type="decimal", precision=4, scale=1)
   */
  private $newValue;

  // Not to be saved in the DB, must be computed every time needed
  private $oldValue;

  /**
   * @ORM\Column(type="string", length=200, nullable=true)
   */
  private $text;

  /**
   * @ORM\ManyToOne(targetEntity="User")
   * @ORM\JoinColumn(name="user", referencedColumnName="id")
   */
  private $user;

  /**
   * @ORM\Column(type="boolean")
   */
  private $discard;

  /**
   * @var DateTime
   * @ORM\Column(type="datetime")
   */
  private $time;

  public function getId() {
    return $this->id;
  }

  public function getOldValue() {
    if($this->oldValue <= 2) return 0;
    else return $this->oldValue;
    return $this->oldValue;
  }

  public function setOldValue($value) {
    $this->oldValue = $value;
  }

  public function getValue() {
    $v = round($this->newValue);
    if($v <= 2) return 0;
    else return $v;
    return $v;
  }

  public function getGauge(): Gauge {
    return $this->gauge;
  }

  public function setGauge(Gauge $gauge) {
    $this->gauge = $gauge;
  }

  /**
   * @param $newValue
   */
  public function setValues($newValue) {
    $this->newValue = $newValue;
    $this->time = new \DateTime("now");
    $this->discard = false;
    $this->user = 1;
    $this->text = NULL;
  }

  public function getTime() {
    return $this->time->format('d.m.Y \v H:i');
  }

  public function getRawTime() {
    return $this->time;
  }

  public function getTimeText() {
    $now = new DateTime;
    $diff = $now->diff($this->time);

    $diff->w = floor($diff->d / 7);
    $diff->d -= $diff->w * 7;

    $string = array(
      'y' => 'y',
      'm' => 'mo',
      'w' => 'w',
      'd' => 'd',
      'h' => 'h',
      'i' => 'min',
      's' => 's',
    );
    foreach ($string as $k => &$v) {
      if ($diff->$k) {
        $v = $diff->$k.''.$v;
      } else {
        unset($string[$k]);
      }
    }

    $string = array_slice($string, 0, 1);
    return implode(', ', $string).' ago';
  }

  public function setText($text) {
    $this->text = $text;
  }

  public function getText() {
    return $this->text;
  }

  public function getUser() {
    return $this->user;
  }

  public function setUser($user) {
    $this->user = $user;
  }

  public function setDiscard() {
    $this->discard = true;
  }

  public function isDiscarded() {
    return $this->discard;
  }

  public function toString() {
    return "GaugeChange: <br><br>".
            "Gauge: ".$this->gauge->getId()."<br><br>".
            "Time: ".$this->time->format('Y-m-d H:i:s').
            "<br>Text: ".$this->text.
            "<br>NewValue: ".$this->newValue;
  }
}

src/Entity/Issue.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IssueRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Table(name="issue")
 */
class Issue extends AbstractSharableEntity {

  public function __construct() {
    parent::__construct();
    $this->gauges = new ArrayCollection();
    $this->oldShareRights = null;
  }

  /**
   * @ORM\ManyToOne(targetEntity="Board", inversedBy="issues")
   * @ORM\JoinColumn(name="id_board", referencedColumnName="id")
   */
  private $board;

  public function setBoard($board_id) {
    $this->board = $board_id;
  }

  /** @return Board */
  public function getBoard() {
    return $this->board;
  }

  /**
   * @ORM\OneToMany(targetEntity="Gauge", mappedBy="issue")
   * @ORM\OrderBy({"position" = "ASC"})
   */
  private $gauges;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $deletedAt;

  public function setDeletedAt($deletedAt) {
    $this->deletedAt = $deletedAt;
  }

  public function isDeleted() {
    return $this->deletedAt !== null;
  }

  public function restore() {
    $this->deletedAt = null;
  }

  /** Variable with array of users that contributed to the issue.
   * Has to be manually set (eg. from boardrepository) */
  private $activeUsers;

  /** Set if the sharing was changed for this Issue only. While this is not null,
   * its not affected by Board sharing rights changes. When its set to its default value,
   * oldShareRights is set to null and it inherits from its parent Board once again.
   * @ORM\Column(type="string", length=32, nullable=true)
   */
  private  $oldShareRights;

  public function getOldShareRights() {
    return $this->oldShareRights;
  }

  public function setOldShareRights($newRight = null) {
    $this->oldShareRights = $newRight;
  }

  public function isOldShareRights() {
    return $this->oldShareRights !== null;
  }

  /**
   * @return Collection|Gauge[]
   */
  public function getGauges()  {
    return $this->gauges;
  }

  public function getGaugesSorted() {
    return usort($this->gauges, array($this, "compare"));
  }

  /** Compares gauges to sort them by position.
   * @param Gauge $a
   * @param Gauge $b
   * @return int
   */
  private function compare($a, $b) {
    return strcmp($a->getPosition(), $b->getPosition());
  }

  /** Array of few latest GaugeChanges */
  private $gaugeCommentLatest;

  /** @var int - number of GaugeChanges for the issue */
  private $gaugeCommentsCount;

  public function getLatestGaugeComments() {
    return $this->gaugeCommentLatest;
  }

  public function getCountGaugeComments() {
    return $this->gaugeCommentsCount;
  }

  public function setLatestGaugeComments($comments) {
    $this->gaugeCommentLatest = $comments;
  }

  public function setCountGaugeComments($count) {
    $this->gaugeCommentsCount = $count;
  }
  /**
   * @param Gauge $gauge
   */
  public function setGauge($gauge) {
    $this->gauges[] = $gauge;
  }

  public function getUrl() {
    return 'i/'.parent::getUrl();
  }

  /**
   * @param array $usersArray
   */
  public function setActiveUsers($usersArray) {
    $this->activeUsers = $usersArray;
  }

  public function getActiveUsers() {
    return $this->activeUsers;
  }
}

src/Controller/IssueController.php
<?php

namespace App\Controller;

use App\Entity\Deadline;
use App\Entity\Gauge;
use App\Entity\GaugeChanges;
use App\Entity\Issue;
use App\Entity\Notification;
use App\Entity\Tips;
use App\Entity\User;
use App\Repository\DeadlineRepository;
use App\Repository\GaugeChangesRepository;
use App\Repository\GaugeRepository;
use App\Repository\IssueRepository;
use App\Repository\NotificationRepository;
use App\Repository\TipsRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class IssueController extends Controller {

  /** Link to redirect to Issue when sharing just one Gauge with user email
   * @Route("/g/{link}/{name}", name="gauge")
   */
  public function gaugeShare($link, $name) {
    return $this->index($link, $name);
  }

  /**
   * @Route("/i/{link}/{name}", name="issue")
   */
  public function index($link, $name) {
    /** @var User $user */
    $user = $this->getUser();

    /** @var IssueRepository $issueRepository */
    $issueRepository = $this->getDoctrine()->getRepository(Issue::class);
    $issue = $issueRepository->getIssueByLink($link, $user);
    // During first access via the link, the order of operations is kind of messed up, so set user rights correctly
    if($issue->getThisUserRights() === null) {
      // force Board entity reload with new user rights
      $issue = $issueRepository->getIssue($issue->getId(), $user, true);
    }
    $gaugeCount = $issueRepository->getNumberOfGauges();
    if($issue->getThisUserRights()->getRights() == Issue::ROLE_GAUGE) {
      /** @var GaugeRepository $gaugeRepository */
      $gaugeRepository = $this->getDoctrine()->getRepository(Gauge::class);
      $gaugeEdit = $gaugeRepository->getBoundGauges($issue, $user);
    }
    else $gaugeEdit = array_fill(0, $gaugeCount, 1);
    /** @var GaugeChangesRepository $gaugeChangesRepository */
    $gaugeChangesRepository = $this->getDoctrine()->getRepository(GaugeChanges::class);
    $changes = $gaugeChangesRepository->getAllChangesForIssue($issue->getId());
    $users = $issueRepository->getAllActiveUsers($issue->getId());

    /** @var DeadlineRepository $deadlineRepository */
    $deadlineRepository = $this->getDoctrine()->getRepository(Deadline::class);
    $deadlines = $deadlineRepository->getDeadlinesForIssue($issue);

    /** @var NotificationRepository $notificationRepository */
    $notificationRepository = $this->getDoctrine()->getRepository(Notification::class);
    $notifications = $notificationRepository->getUnreadNotifications($user);

    /** @var TipsRepository $tipsRepository */
    $tipsRepository = $this->getDoctrine()->getRepository(Tips::class);
    $tips = $tipsRepository->getNewTipsForPage('issue', $user->getAnonymousLink());

    return $this->render('issue/issue-detail.html.twig',
      ["issue" => $issue, "changes" => $changes, "gaugeCount" => $gaugeCount,
       "users" => array_reverse($users), "deadlines" => $deadlines,
       'notifications' => $notifications, "tips" => $tips, "gaugeEdit" => $gaugeEdit]);
  }

}

templates/issue/comment.html.twig
<div class="media mb-3">
    <span title="{{ change.user.username }}" class="ml-1 mr-3 mt-2">
        {{ include('user/user-icon.html.twig', {'user': change.user, 'size': 'big'}) }}
    </span>
    <div class="media-body">
        <div class="d-flex justify-content-between">
            <span style="color: {{ change.gauge.color }}">{{ change.gauge.name }}: {{ change.oldValue }}
                <i class="fas fa-angle-right"></i> <b>{{ change.value }}</b> %</span>
            <small class="float-right text-secondary" title="{{ change.time }}">{{ change.timeText }}</small>
        </div>
        <div class="d-flex justify-content-between">
            <div class="pl-1 float-left">
                {% if change.text|length > 0 %}
                        {{ change.text }}
                {% endif %}
            </div>
            {#<a href="" class="float-right">+1</a>#}
        </div>
    </div>
</div>

templates/issue/commentsTab.html.twig
<div class="media mb-5" id="gaugeChangeCommit" style="display: none">
    <i class="far fa-2x fa-user-circle align-self-start mr-5"></i>
    <div class="media-body">
        <h5 class="mt-0" id="gaugeCommentHeadline"></h5>
        <textarea class="form-control" id="gaugeCommentText" rows="2"></textarea>
    </div>
    <div class="align-self-end mx-0" style="position: relative; left: 20px;">
        <button class="btn btn-success" id="gaugeChangeConfirmBtn"><i class="fas fa-check"></i></button>
    </div>
    <div class="align-self-start mx-0" style="position: relative; left: -20px;">
        <button class="btn btn-danger" id="gaugeChangeResetBtn"><i class="fas fa-times"></i></button>
    </div>
    <hr>
</div>
<div id="gaugeComments">
    {% for change in changes %}
        {{ include('issue/comment.html.twig', {'change': change}) }}
    {% endfor %}
    {% if changes|length == 0 %}
        <p class="text-center text-secondary mt-5" id="gaugeCommentNoChangesText">
            There are no changes yet!
        </p>
    {% endif %}
</div>
<button class="btn btn-secondary mx-auto" style="display: none; width: 130px;" data-field="hide"
        id="gaugeCommentShowAllBtn"><i class="fas fa-sync"></i> Show all</button>
<div class="m-0 p-0">&nbsp;</div>

templates/issue/deadlineList.html.twig
{% for deadline in deadlines %}
    <div class="mb-md-4 ml-3" id="deadline{{ deadline.id }}">
        <div class="d-flex justify-content-between pr-3 hover">
            <h5 style="color: {{ deadline.color }}">{{ deadline.name }}</h5>
            {% if (issue is defined and issue.canUserWrite) or not issue is defined %}
                <div class="hover-hidden">
                    {#<button type="button" class="nobtn startTooltip pointer deadlineEdit"#}
                    {#value="{{ deadline.id }}"#}
                    {#data-toggle="tooltip" data-placement="top" title="Edit deadline">#}
                    {#<i class="fas fa-edit mr-2 text-secondary"></i>#}
                    {#</button>#}
                    <button type="button" class="nobtn startTooltip pointer deadlineDelete"
                            value="{{ deadline.id }}"
                            data-toggle="tooltip" data-placement="top" title="Delete deadline">
                        <i class="fas fa-trash-alt text-secondary"></i>
                    </button>
                </div>
                <h5 class="hover-shown">
                    {{ deadline.gaugeOwner }}
                </h5>
            {% else %}
                <div class="float-right">
                    <h5>{{ deadline.gaugeOwner }}</h5>
                </div>
            {% endif %}
        </div>
        {% if deadline.text|length > 0 %}
            <p class="small m-0 p-0 mb-1">{{ deadline.text }}</p>
        {% endif %}
        <div class="row">
            <div class="col-2 d-none d-md-flex p-0 pl-md-3 m-0">{{ deadline.start }}</div>
            <div class="col-sm-12 col-md-8">
                <div class="progress bg-muted mt-1">
                    <div class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"
                         style="width: {{ deadline.percentage }}%; background-color: {{ deadline.color }}">
                        {% if  deadline.percentage == 100 %} Time's up!
                        {% elseif deadline.percentage > 20 %}
                            {{ deadline.daysLeft }} day{% if deadline.daysLeft > 1 %}s{% endif %} left
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-2 d-none d-md-flex p-0 pl-md-3 m-0">{{ deadline.end }}</div>
        </div>
    </div>
{% endfor %}

templates/issue/deadlinesSelect.html.twig
<div class="form-inline">

    <select class="form-control mb-3 col-10" id="deadlineTasks">
        {% set exists = false %}
        {% for deadline in deadlines %}
            {% if deadline.gaugeId == 'issue' %}{% set exists = true %}{% endif %}
        {% endfor %}
        <option value="issue">Issue: {{ issue.name }}  {% if exists == false %}(create new){% endif %}</option>
        {% for task in issue.gauges %}
            {% set exists = false %}
            {% for deadline in deadlines %}
                {% if deadline.gaugeId == task.id %}{% set exists = true %}{% endif %}
            {% endfor %}
            <option value="{{ task.id }}">Task: {{ task.name }} {% if exists == false %}(create new){% endif %}</option>
        {% endfor %}
    </select>

    <button type="button" class="nobtn pointer deadlineDelete col-2 mb-3 d-none"
            value="55" id="deadlineTrash">
        <i class="fas fa-2x fa-trash-alt text-secondary"></i>
    </button>
</div>

<div class="d-none" id="deadlinesData">
    {% for deadline in deadlines %}
        <div id="deadline{{ deadline.gaugeId }}">
            <input type="hidden" value="{{ deadline.startPicker }}">
            <input type="hidden" value="{{ deadline.endPicker }}">
            <input type="hidden" value="{{ deadline.text }}">
            <input type="hidden" value="{{ deadline.id }}">
        </div>
    {% endfor %}
</div>

templates/issue/deadlinesTab.html.twig
<div class="d-flex justify-content-between">
    <h3 class="text-smallcaps">{% trans %}tooltip_deadlines{% endtrans %}:</h3>
    <button type="button" class="close float-right gaugeCloseBtn" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<h6>Link deadline to:</h6>
<div id="deadlinesSelect">
    {{ include('issue/deadlinesSelect.html.twig', {'deadlines': deadlines, 'issue': issue}) }}
</div>
<div id="deadlinesDatepicker">
    <div class="input-daterange input-group" id="datepicker">
        <input type="text" class="input-sm form-control bg-white"
               name="start" placeholder="Start date" id="deadlineStart" readonly />
        <span class="input-group-addon px-3">to</span>
        <input type="text" class="input-sm form-control bg-white"
               name="end" placeholder="End date" id="deadlineEnd" readonly />
    </div>
</div>

<div class="form-group mt-2">
    <textarea class="form-control" id="deadlineTextarea" rows="1" placeholder="Deadline description"></textarea>
</div>

<button class="btn btn-success mx-auto pointer mt-3 d-block" style="width: 130px;"
        id="issueDeadlineSaveBtn">{% trans %}btn_save{% endtrans %}</button>
<div class="m-0 p-0 d-md-block d-lg-none">&nbsp;</div>

templates/issue/edit-comment.html.twig
<div class="media">
    <i class="fas fa-2x fa-user-circle align-self-start mr-4"></i>
    <div class="media-body mb-3">
        <div class="d-flex justify-content-between">
            <h5 style="color: {{ change.gauge.color }}">{{ change.gauge.name }}: {{ change.oldValue }} % -> {{ change.value }} %</h5>
            <span class="float-right">{{ change.time }}</span>
        </div>
        {% if change.text|length > 0 %}
            <div class="border border-secondary rounded px-2 py-1">
                {{ change.text }}
            </div>
        {% endif %}
    </div>
</div>

templates/issue/editIssueTab.html.twig
<div class="d-flex justify-content-between">
    <h3 class="text-smallcaps">{% trans %}btn_edit{% endtrans %} {% trans %}issue{% endtrans %}:</h3>
    <button type="button" class="close float-right gaugeCloseBtn" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<br>
<input type="text" class="form-control" placeholder="Issue name" id="issueEditName" value="{{ issue.name }}">
<input type="hidden" id="issueEditId" value="{{ issue.id }}">
<br>
<button class="btn btn-success mx-auto pointer" style="display: block; width: 130px;"
        id="issueEditSaveBtn">{% trans %}btn_save{% endtrans %}</button>

{% if issue.canUserManage %}
    <div class="mt-5">
        <div class="d-flex justify-content-between">
            <div>
                <div class="row">
                    <div class="col-2">
                        <i class="fas fa-2x fa-exclamation-triangle text-warning mt-2"></i>
                    </div>
                    <div class="col-10">
                        <b class="float-left">{% trans %}btn_delete{% endtrans %} {% trans %}issue{% endtrans %}</b><br>
                        Permanently deletes this one issue.
                    </div>
                </div>
            </div>
            <button class="btn btn-outline-danger pointer float-right" id="issueEditDelete">
                {% trans %}btn_delete{% endtrans %} {% trans %}issue{% endtrans %}</button>
        </div>
        <input type="hidden" id="issueDeleteId" value="{{ issue.pageId }}">
    </div>
{% endif %}

<div class="m-0 p-0 d-md-block d-lg-none">&nbsp;</div>

templates/issue/issue-overview.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{  parent() }}
    <script src="{{ asset('build/chart.js') }}"></script>
    <script>
        var options = {
            scales: {
                yAxes: [{
                    gridLines : {
                        display : false
                    },
                    ticks: {
                        display: false,
                        max: 100,
                        beginAtZero:true
                    }
                }],
                xAxes: [{
                    gridLines : {
                        display : false
                    },
                    ticks: {
                        maxRotation: 0
                    }
                }]
            },
            legend: {
                display : false
            },
            tooltips: {
                custom: function(tooltip) {
                    if (!tooltip) return;
                },
                callbacks: {
                    // use label callback to return the desired label
                    label: function(tooltipItem, data) {
                        return ' '+tooltipItem.xLabel;
                    },
                    // remove title
                    title: function(tooltipItem, data) {}
                }
            }
        };
    </script>
{% endblock %}

{% block body %}

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
        <h1>{{  board.name }}</h1>
        <div class="card-deck">
            {% for issue in board.issues %}
                <div class="card bg-dark mb-3" >
                    <h4 class="card-header text-white">
                        <a href="{{ path('issue', {'link': issue.link}) }}">{{ issue.name }}</a>
                    </h4>
                    <div class="card-body bg-light">
                        {{ include('graphs/graph.html.twig', { 'gauges': issue.gauges,
                            'gauge_name': issue.link,
                            'issue_id': issue.id}) }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>

{% endblock %}

templates/issue/issue.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{  parent() }}
    <script src="{{ asset('build/chart.js') }}"></script>
    <script>
        var options = {
            scales: {
                yAxes: [{
                    gridLines : {
                        display : false
                    },
                    ticks: {
                        display: false,
                        max: 100,
                        beginAtZero:true
                    }
                }],
                xAxes: [{
                    gridLines : {
                        display : false
                    },
                    ticks: {
                        maxRotation: 0
                    }
                }]
            },
            legend: {
                display : false
            },
            tooltips: {
                custom: function(tooltip) {
                    if (!tooltip) return;
                },
                callbacks: {
                    // use label callback to return the desired label
                    label: function(tooltipItem, data) {
                        return ' '+tooltipItem.xLabel;
                    },
                    // remove title
                    title: function(tooltipItem, data) {}
                }
            }
        };
    </script>
{% endblock %}

{% block body %}

    <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
        <h1>{{  board.name }}</h1>
        <div class="card-deck">
            {% for issue in board.issues %}
                <div class="card bg-dark mb-3" >
                    <h4 class="card-header text-white">
                        <a href="{{ path('issue', {'link': issue.link}) }}">{{ issue.name }}</a>
                    </h4>
                    <div class="card-body bg-light">
                        {{ include('graphs/graph.html.twig', { 'gauges': issue.gauges,
                            'gauge_name': issue.link,
                            'issue_id': issue.id}) }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>

{% endblock %}

templates/issue/question.html.twig
<h2 class="text-center">Are you sure you want to <span id="questionText"></span>?</h2>
<input type="hidden" id="questionCall" value="">
<input type="hidden" id="questionValue1" value="">
<input type="hidden" id="questionValue2" value="">

<div class="row px-5 mt-5">
    <button class="btn btn-success mx-auto pointer" style="display: block; width: 130px;"
            id="questionYes">Yes</button>
    <button class="btn btn-danger mx-auto pointer" style="display: block; width: 130px;"
            id="questionNo">No</button>
</div>