src/Entity/Board.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BoardRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Table(name="board")
 */
class Board extends AbstractSharableEntity {

  public function __construct() {
    parent::__construct();
    $this->issues = new ArrayCollection();
    $this->favorite = false;
    $this->archivedAt = null;
  }

  /**
   * @ORM\OneToMany(targetEntity="Issue", mappedBy="board")
   */
  private $issues;

  /**
   * @return Collection|Issue[]
   */
  public function getIssues() {
    return $this->issues;
  }

  public function removeIssue($issue) {
    $this->issues->removeElement($issue);
  }

  /**
   * @param Issue $issue
   */
  public function setIssue($issue) {
    $this->issues[] = $issue;
  }

  public function getUrl() {
    return 'b/'.parent::getUrl();
  }

  /** Users with rights to see this board */
  private $users;

  public function setUsers($users) {
    $this->users = $users;
  }

  public function getUsers() {
    return $this->users;
  }

  /** Variable with array of users that contributed to this board.
   * Has to be manually set (eg. from controllers) */
  private $activeUsers;


  /**
   * @ORM\Column(type="string", length=7)
   */
  private $color;

  public function setColor($color) {
    if(strlen($color) == 7)
      $this->color = $color;
    elseif(strlen($color) == 6)
      $this->color = '#'.$color;
    else
      $this->color = '#008ba3';
  }

  public function getColor() {
    return $this->color;
  }

  public function getBackground() {
    return 'bg-'.substr($this->color,1);
  }

  /**
   * @var \DateTime
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $deletedAt;

  public function setDeletedAt($deletedAt) {
    $this->deletedAt = $deletedAt;
  }

  public function isDeleted() {
    return $this->deletedAt !== null;
  }

  /**
   * @var \DateTime
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $archivedAt;

  public function archive() {
    $this->archivedAt = new \DateTime("now");
  }

  public function isArchived() {
    return $this->archivedAt !== null;
  }

  public function getArchivedTime() {
    if($this->archivedAt === null)
      return '';
    else
      return $this->archivedAt->format('M Y');
  }

  /**
   * @param array $usersArray
   */
  public function setActiveUsers($usersArray) {
    $this->activeUsers = $usersArray;
  }

  public function getActiveUsers() {
    return $this->activeUsers;
  }
}

src/Entity/Notification.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NotificationRepository")
 * @ORM\Table(name="notification")
 */
class Notification {
  /**
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=512)
   */
  private $text;

  /**
   * @ORM\Column(type="string", length=256)
   */
  private $url;

  /**
   * @ORM\ManyToOne(targetEntity="User")
   * @ORM\JoinColumn(name="id_user", referencedColumnName="id")
   */
  private $user;

  /**
   * @ORM\ManyToOne(targetEntity="User")
   * @ORM\JoinColumn(name="id_creator", referencedColumnName="id")
   */
  private $creator;

  /**
   * @var DateTime $shown
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $shown;

  /**
   * @var DateTime $created
   * @ORM\Column(type="datetime")
   */
  private $created;

  public function setDate() {
    $this->created = new DateTime("now");
  }

  public function setShown() {
    $this->shown = new DateTime("now");
  }

  /** @param User $creator */
  public function setCreator($creator) {
    $this->creator = $creator;
  }

  /** @param UserInterface $user */
  public function setUser($user) {
    $this->user = $user;
  }

  public function setText($text) {
    $this->text = $text;
  }

  public function setUrl($url) {
    $this->url = $url;
  }

  public function getText() {
    return $this->text;
  }

  public function getLink() {
    return '../../'.$this->url;
  }

  public function getDate() {
    return $this->created->format('d. m. Y \v H:i');
  }

  public function isShown() {
    return $this->shown !== null;
  }

  public function getShown() {
    return $this->shown->format('d. m. Y \v H:i');
  }

  public function getDateText() {
    $now = new DateTime;
    $diff = $now->diff($this->created);

    $diff->w = floor($diff->d / 7);
    $diff->d -= $diff->w * 7;

    $string = array(
      'y' => 'y',
      'm' => 'mo',
      'w' => 'w',
      'd' => 'd',
      'h' => 'h',
      'i' => 'm',
      's' => 's',
    );
    foreach ($string as $k => &$v) {
      if ($diff->$k) {
        $v = $diff->$k.''.$v;
      } else {
        unset($string[$k]);
      }
    }

    $string = array_slice($string, 0, 1);
    return implode(', ', $string).'<br>ago';
  }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Welcome!{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block stylesheets %}
        <link rel="icon" type="image/x-icon" href="{{ asset('build/images/graph.59420c62.ico') }}" />
        <link rel="stylesheet" href="{{ asset('build/bootstrap.css') }}" />
        <link rel="stylesheet" href="{{ asset('build/app.css') }}" />
        <script src="{{ asset('build/manifest.js') }}"></script>
        <script src="{{ asset('build/vendor.js') }}"></script>
        {#<script src="{{ asset('build/bootjs.js') }}"></script>#}
        {#<script src="{{ asset('build/app-bundle.js') }}"></script>#}
        <script src="{{ asset('build/fonts-all.js') }}"></script>
        <script src="{{ asset('build/fonts-solid.js') }}"></script>
        {% if tips is defined and  tips|length > 0 %}
            <script src="{{ asset('build/tips.js') }}"></script>
            <link rel="stylesheet" href="{{ asset('build/tips-style.css') }}" />
        {% endif %}
    {% endblock %}
</head>
<body class="bg-light">
{% block menu %}
    <header>
        <nav id="topNavBar" class="navbar navbar-expand-md navbar-dark fixed-top
            {% if board is defined %}{% if board.isArchived %}bg-secondary{% else %}{{ board.background }}{% endif %}
            {%  else  %}my-primary-dark{% endif %}">
            <div class="container">
                <a href="{{ url('dashboard') }}" class="navbar-brand mr-5 m-0 p-0">
                    <img src="{{ asset('build/images/logo.15ff2d0a.png') }}" height="38px" class="m-0 p-0">
                </a>
                <div class="btn-group">
                    {% if board is defined %}
                        <a href="../../{{ board.url }}">
                            <button class="btn menubtn text-light pointer
                                {% if board.isArchived %}bg-secondary{% else %}{{ board.background }}{% endif %}"
                                    id="navbarProjectNameBtn">
                                {{ board.name }}
                            </button>
                        </a>
                        <button type="button" id="navbarProjectBtn" data-toggle="dropdown"
                                class="d-none d-md-flex btn menubtn dropdown-toggle dropdown-toggle-split pointer
                                text-light {% if board.isArchived %}bg-secondary{% else %}{{ board.background }}{% endif %}"
                                aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only"> {% trans %}others{% endtrans %}</span>
                        </button>
                    {% elseif not(is_granted('ROLE_ANONYMOUS')) or (boards is defined and boards|length > 0) %}
                        <button type="button" class="btn d-none d-md-block menubtn dropdown-toggle pointer text-light
                        my-primary-dark"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="navbarProjectBtn">
                            {% trans %}projects{% endtrans %}
                        </button>
                    {% endif %}
                    <div class="dropdown-menu" id="navbarProjectsBody"></div>
                </div>
                <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                    <div class="d-flex justify-content-end w-100">
                    {#<div class="d-flex justify-content-between w-100">#}
                        {#<div class="form-inline ml-3">#}
                            {#<div class="btn-group">#}
                                {#<input class="form-control rounded-left" type="search" placeholder="Search"#}
                                       {#aria-label="Search" size="12">#}
                                {#<button class="btn" type="submit">Search</button>#}
                            {#</div>#}
                        {#</div>#}
                        {#<ul class="mx-auto"></ul>#}
                        {% if notifications is defined %}
                            {{ include('navbar-notifications.html.twig', {'notifications': notifications}) }}
                        {% endif %}
                        {{ include('navbar-user.html.twig') }}
                    </div>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}

<div class="container" id="mainContainer">
    <div class="row">
        {% block body %}{% endblock %}
    </div>
    <div id="tips-overlay"></div>
    {{ include('board/new-modal.html.twig') }}
</div>
<div class="fixed-bottom" >
    <div class="btn-group dropup rounded m-1">
         <button data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="bugReportBtn"
                 class="btn btn-secondary pointer dropdown-toggle"> Report bug</button>
        <div class="dropdown-menu p-2">
            <label for="bugReportText">This is alpha version of this application. Any feedback will be really
                appreciated.</label>
            <textarea id="bugReportText"></textarea>
            <button class="btn" id="bugReportSend">Send</button>
        </div>
    </div>
</div>

{% block javascripts %}
{% endblock %}
</body>
</html>

templates/bugs.html.twig
{% for bug in bugs %}
    {{ bug.user.username }}: {{ bug.text }}<br><br>
{% endfor %}

templates/navbar-notifications.html.twig
<div class="dropdown float-right">
    <button class="nobtn float-right pointer m-0 p-0" data-toggle="dropdown" aria-haspopup="false"
            type="button" aria-expanded="true" id="dropdownMenuNotifications">
        <span class="mr-3">
            <i class="fas fa-bell text-light fa-2x mt-2"></i>
            {% if notifications['count'] > 0 %}
                <span class="fa-layers-counter fa-3x mr-1" id="notificationCount"
                      style="background:Tomato">{{ notifications['count'] }}</span>
            {% endif %}
        </span>
    </button>
    <div class="dropdown-menu my-dropdown mt-2" aria-labelledby="dropdownMenuNotifications"
          style="right: 10px; left: auto;">
        <div class="text-secondary text-center">{% trans %}notifications{% endtrans %}:</div>
        <div class="dropdown-divider"></div>
        {% if notifications['data']|length > 0 %}
            {% for note in notifications['data']  %}
                <div class="dropdown-item">
                    <div class="row">
                        <div class="col-10 pr-5">
                            {% if note.link|length > 0 %}
                                <a href="{{ note.link }}" class="{% if note.isShown %}text-secondary{% else %}text-dark{% endif %}"
                               title="{% if note.isShown %}{% trans %}displayed{% endtrans %} {{ note.shown }} {% else %}{% trans %}created{% endtrans %} {{ note.date }}{% endif %}">
                                {{ note.text | raw }}
                                </a>
                            {% else %}
                                <span class="{% if note.isShown %}text-secondary{% else %}text-dark{% endif %}">
                                    {{ note.text | raw }}
                                </span>
                            {% endif %}
                        </div>
                        <div class="col-2">
                            <small class="text-secondary " title="{{ note.date }}">
                                {{ note.dateText | raw }}</small>
                        </div>
                    </div>
                </div>
                <div class="dropdown-divider m-0"></div>
            {% endfor %}
        {% else %}
            <div class="p-2 text-dark text-center">{% trans %}no_notifications{% endtrans %}</div>
        {% endif %}
    </div>
</div>

templates/navbar-projects.html.twig
{% if favorite|length > 0 and favorite|length != boards|length %}
    <span class="text-secondary pl-2">{% trans %}fav_projects{% endtrans %}</span>
    {% for role in favorite %}
        <div class="m-1">
            <a class="dropdown-item {{ role.board.background }}-light rounded"
               href="../../{{ role.board.url }}"> {{ role.board.name }}
            </a>
        </div>
    {% endfor %}
{% endif %}

<a href="{{ path('dashboard') }}" class="text-secondary pl-2 pt-5">{% trans %}my_projects{% endtrans %}</a>
{% for role in boards %}
    <div class="m-1">
        <a class="dropdown-item {{ role.board.background }}-light rounded"
           href="../../{{ role.board.url }}"> {{ role.board.name }}
        </a>
    </div>
{% endfor %}

 {% if not is_granted('ROLE_ANONYMOUS') %}
    <div class="dropdown-divider"></div>
    <button class="dropdown-item pointer" type="button" data-toggle="modal" data-target="#modalNewBoard">
        {% trans %}new_project{% endtrans %}</button>
{% endif %}

templates/navbar-user.html.twig
<div class="dropdown float-right">
    <button class="nobtn float-right pointer m-0 p-0 " data-toggle="dropdown" aria-haspopup="false"
            type="button" aria-expanded="true" id="dropdownMenuUser">
        {{ include('user/user-icon.html.twig', {'user': app.user, 'size': 'big'}) }}
    </button>
    <div class="dropdown-menu my-dropdown mt-2" aria-labelledby="dropdownMenuUser" style="right: 10px; left: auto;"
         id="navbar-user-menu">
        <label title="{% trans %}title_changeUser{% endtrans %}" for="navbar-username">
            <span class="input-group">
                <div class="ml-2 mt-1">
                    {{ include('user/user-icon.html.twig', {'user': app.user, 'size': 'small'}) }}
                </div>
                <input type="text" value="{{ app.user.username }}" id="navbar-username"
                       class="text-left borderless text-dark bg-white pl-1" disabled size="12">
                <input type="hidden" value="{{ app.user.username }}" id="user-name">
                <input type="hidden" value="{{ app.user.id }}" id="user-id">
                <span class="text-secondary pointer mt-2 m-1" id="navbar-user-edit"><i class="fas fa-1x fa-edit"></i></span>
            </span>
        </label>
        <button type="button" class="dropdown-item btn-link pointer" id="language">
            {% trans %}language{% endtrans %}: {{ app.request.locale }}</button>

        <div class="pl-4 d-none" id="languageChange">
            <label>
                <select class="custom-select pointer" id="languageSelect">
                    <option value="en" {% if app.request.locale == 'en' %}selected{% endif %}>English</option>
                    <option value="cz" {% if app.request.locale == 'cz' %}selected{% endif %}>Česky</option>
                </select>
            </label>
        </div>
        <div class="dropdown-divider"></div>
            <a class="dropdown-item btn-link pointer" href="{{ path('myDeadlines') }}">
                {% trans %}my_deadlines{% endtrans %}
            </a>
        <div class="dropdown-divider"></div>
        {% if is_granted('ROLE_ANONYMOUS') %}
            <a class="dropdown-item pointer" href="{{ path('hwi_oauth_service_redirect', {'service': 'google'}) }}">
                {% trans %}login_google{% endtrans %}</a>
        {% else %}
            <a class="dropdown-item pointer" href="{{ url('logout') }}">{% trans %}logout{% endtrans %}</a>
        {% endif %}
    </div>
</div>