src/Entity/Board.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BoardRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Table(name="board")
 */
class Board extends AbstractSharableEntity {

  public function __construct() {
    parent::__construct();
    $this->issues = new ArrayCollection();
    $this->favorite = false;
    $this->archivedAt = null;
  }

  /**
   * @ORM\OneToMany(targetEntity="Issue", mappedBy="board")
   */
  private $issues;

  /**
   * @return Collection|Issue[]
   */
  public function getIssues() {
    return $this->issues;
  }

  public function removeIssue($issue) {
    $this->issues->removeElement($issue);
  }

  /**
   * @param Issue $issue
   */
  public function setIssue($issue) {
    $this->issues[] = $issue;
  }

  public function getUrl() {
    return 'b/'.parent::getUrl();
  }

  /** Users with rights to see this board */
  private $users;

  public function setUsers($users) {
    $this->users = $users;
  }

  public function getUsers() {
    return $this->users;
  }

  /** Variable with array of users that contributed to this board.
   * Has to be manually set (eg. from controllers) */
  private $activeUsers;


  /**
   * @ORM\Column(type="string", length=7)
   */
  private $color;

  public function setColor($color) {
    if(strlen($color) == 7)
      $this->color = $color;
    elseif(strlen($color) == 6)
      $this->color = '#'.$color;
    else
      $this->color = '#008ba3';
  }

  public function getColor() {
    return $this->color;
  }

  public function getBackground() {
    return 'bg-'.substr($this->color,1);
  }

  /**
   * @var \DateTime
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $deletedAt;

  public function setDeletedAt($deletedAt) {
    $this->deletedAt = $deletedAt;
  }

  public function isDeleted() {
    return $this->deletedAt !== null;
  }

  /**
   * @var \DateTime
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $archivedAt;

  public function archive() {
    $this->archivedAt = new \DateTime("now");
  }

  public function isArchived() {
    return $this->archivedAt !== null;
  }

  public function getArchivedTime() {
    if($this->archivedAt === null)
      return '';
    else
      return $this->archivedAt->format('M Y');
  }

  /**
   * @param array $usersArray
   */
  public function setActiveUsers($usersArray) {
    $this->activeUsers = $usersArray;
  }

  public function getActiveUsers() {
    return $this->activeUsers;
  }
}

src/Entity/Issue.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IssueRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Table(name="issue")
 */
class Issue extends AbstractSharableEntity {

  public function __construct() {
    parent::__construct();
    $this->gauges = new ArrayCollection();
    $this->oldShareRights = null;
  }

  /**
   * @ORM\ManyToOne(targetEntity="Board", inversedBy="issues")
   * @ORM\JoinColumn(name="id_board", referencedColumnName="id")
   */
  private $board;

  public function setBoard($board_id) {
    $this->board = $board_id;
  }

  /** @return Board */
  public function getBoard() {
    return $this->board;
  }

  /**
   * @ORM\OneToMany(targetEntity="Gauge", mappedBy="issue")
   * @ORM\OrderBy({"position" = "ASC"})
   */
  private $gauges;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  private $deletedAt;

  public function setDeletedAt($deletedAt) {
    $this->deletedAt = $deletedAt;
  }

  public function isDeleted() {
    return $this->deletedAt !== null;
  }

  public function restore() {
    $this->deletedAt = null;
  }

  /** Variable with array of users that contributed to the issue.
   * Has to be manually set (eg. from boardrepository) */
  private $activeUsers;

  /** Set if the sharing was changed for this Issue only. While this is not null,
   * its not affected by Board sharing rights changes. When its set to its default value,
   * oldShareRights is set to null and it inherits from its parent Board once again.
   * @ORM\Column(type="string", length=32, nullable=true)
   */
  private  $oldShareRights;

  public function getOldShareRights() {
    return $this->oldShareRights;
  }

  public function setOldShareRights($newRight = null) {
    $this->oldShareRights = $newRight;
  }

  public function isOldShareRights() {
    return $this->oldShareRights !== null;
  }

  /**
   * @return Collection|Gauge[]
   */
  public function getGauges()  {
    return $this->gauges;
  }

  public function getGaugesSorted() {
    return usort($this->gauges, array($this, "compare"));
  }

  /** Compares gauges to sort them by position.
   * @param Gauge $a
   * @param Gauge $b
   * @return int
   */
  private function compare($a, $b) {
    return strcmp($a->getPosition(), $b->getPosition());
  }

  /** Array of few latest GaugeChanges */
  private $gaugeCommentLatest;

  /** @var int - number of GaugeChanges for the issue */
  private $gaugeCommentsCount;

  public function getLatestGaugeComments() {
    return $this->gaugeCommentLatest;
  }

  public function getCountGaugeComments() {
    return $this->gaugeCommentsCount;
  }

  public function setLatestGaugeComments($comments) {
    $this->gaugeCommentLatest = $comments;
  }

  public function setCountGaugeComments($count) {
    $this->gaugeCommentsCount = $count;
  }
  /**
   * @param Gauge $gauge
   */
  public function setGauge($gauge) {
    $this->gauges[] = $gauge;
  }

  public function getUrl() {
    return 'i/'.parent::getUrl();
  }

  /**
   * @param array $usersArray
   */
  public function setActiveUsers($usersArray) {
    $this->activeUsers = $usersArray;
  }

  public function getActiveUsers() {
    return $this->activeUsers;
  }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Board;
use App\Entity\BoardRole;
use App\Entity\Bug;
use App\Entity\Deadline;
use App\Entity\Notification;
use App\Entity\Tips;
use App\Entity\User;
use App\Repository\BoardRepository;
use App\Repository\BoardRoleRepository;
use App\Repository\DeadlineRepository;
use App\Repository\NotificationRepository;
use App\Repository\TipsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DashboardController extends Controller {

  /**
   * @Route("/", name="homepage")
   */
  public function index() {
    /** @var BoardRoleRepository $boardRole */
    $boardRole = $this->getDoctrine()->getRepository(BoardRole::class);
    /** @var BoardRole[][] $boards */
    $boards = $boardRole->getUserBoardsAndFavorite($this->getUser());
    if(sizeof($boards['boards']) == 0 && sizeof($boards['archived']) == 0) { // user has nothing yet
      return $this->showDefaultHomepage();
    }
    elseif(sizeof($boards['boards']) == 1 or sizeof($boards['favorite']) == 1) {
      if(sizeof($boards['boards']) == 1)
        return $this->showSingleBoard($boards['boards'][0]);
      else
        return $this->showSingleBoard($boards['favorite'][0]);
    }
    else { // user has more than one board
      return $this->showMoreBoards($boards);
    }
  }

  /**
   * @Route("/bugs", name="bugs")
   */
  public function bugs() {
    $entityManager = $this->getDoctrine()->getManager();
    $records = $entityManager->getRepository(Bug::class)->findAll();
    return $this->render('bugs.html.twig', ['bugs' => $records]);
  }

  /**
   * @Route("/dashboard", name="dashboard")
   */
  public function dashboard() {
    /** @var BoardRoleRepository $boardRole */
    $boardRole = $this->getDoctrine()->getRepository(BoardRole::class);
    /** @var BoardRole[][] $boards */
    $boards = $boardRole->getUserBoardsAndFavorite($this->getUser());
    if(sizeof($boards['boards']) == 0 && sizeof($boards['archived']) == 0) { // user has nothing yet
      return $this->showDefaultHomepage();
    }
    else { // user has more than one board
      return $this->showMoreBoards($boards);
    }
  }

  private function showDefaultHomepage() {
    /** @var TipsRepository $tipsRepository */
    $tipsRepository = $this->getDoctrine()->getRepository(Tips::class);
    /** @var User $user */
    $user = $this->getUser();
    $tips = $tipsRepository->getNewTipsForPage('dashboard', $user->getAnonymousLink());
    /** @var NotificationRepository $notificationRepository */
    $notificationRepository = $this->getDoctrine()->getRepository(Notification::class);
    $notifications = $notificationRepository->getUnreadNotifications($user);
    return $this->render('dashboard/homepage.html.twig',
      ['boards' => '', 'favorite' => [], 'tips' => $tips,
       'notifications' => $notifications, 'archived' => []]);
  }

  /** @param BoardRole $board */
  private function showSingleBoard($board) {
    return $this->redirectToRoute('board', array('link' => $board->getBoard()->getPageId(),
                                                 'name' => $board->getBoard()->getLink()));
  }

  /** @param BoardRole[][] $boards */
  private function  showMoreBoards($boards) {
    /** @var DeadlineRepository $deadlineRepository */
    $deadlineRepository = $this->getDoctrine()->getRepository(Deadline::class);
    $deadlines = $deadlineRepository->getDeadlinesForUser($this->getUser());

    /** @var BoardRepository $boardRepository */
    $boardRepository = $this->getDoctrine()->getRepository(Board::class);
    foreach($boards['boards'] as $board) { // get all users that contributed to all boards
      $active = $boardRepository->getAllActiveUsers($board->getBoard(), 4);
      $board->getBoard()->setActiveUsers($active);
    }
    /** @var NotificationRepository $notificationRepository */
    $notificationRepository = $this->getDoctrine()->getRepository(Notification::class);
    $notifications = $notificationRepository->getUnreadNotifications($this->getUser());
    return $this->render('dashboard/homepage.html.twig',
      ['boards' => $boards['boards'], 'favorite' => $boards['favorite'],
       'notifications' => $notifications, 'archived' => $boards['archived'], 'deadlines' => $deadlines]);

  }
}

templates/dashboard/board-card.html.twig
<div class="col-md-3 p-0 mb-3" id="{{ section }}{{ role.board.pageId }}">
    <div class="card">
        <div class="card-header rounded-0 pb-3 {{ role.board.background }}">
            <button class="nobtn pointer float-right dashboardFavorite {{ section }}orite"
                    id="{{ section }}btn{{ role.board.pageId }}">
                {% if role.favorite %}
                    <i class="fas fa-star"></i>
                {% else %}
                    <i class="far fa-star"></i>
                {% endif %}
            </button>
        </div>
        <div class="card-body mb-4 pb-2">
            <div class="position-absolute" style="height: 1px">
                <div class="dashboard-userlist">
                    {% for user in role.board.activeUsers %}
                        {{ include('user/user-icon.html.twig', {'user': user, 'size': 'small', 'entity': role.board}) }}
                    {% endfor %}
                </div>
            </div>
            <h5 class="card-title">
                <a href="./{{ role.board.url }}">{{ role.board.name }}</a>
            </h5>
        </div>
    </div>
</div>

templates/dashboard/board-overview.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{  parent() }}
    <script src="{{ asset('build/chart.js') }}"></script>
    <script src="{{ asset('build/dashboard.js') }}"></script>
    <script src="{{ asset('build/issue-share.js') }}"></script>
    <script src="{{ asset('build/typeahead.js') }}"></script>
    <script>
        var options = {
            scales: {
                yAxes: [{
                    gridLines : {
                        display : false,
                        drawBorder: false
                    },
                    ticks: {
                        display: false,
                        max: 100,
                        beginAtZero:true
                    }
                }],
                xAxes: [{
                    gridLines : {
                        display : false
                    },
                    ticks: {
                        maxRotation: 0
                    }
                }]
            },
            legend: {
                display : false
            },
            layout: {
                padding: {
                    left: 0,
                    right: 0,
                    top: 0,
                    bottom: 0
                }
            },
            tooltips: {
                custom: function(tooltip) {
                    if (!tooltip) return;
                },
                callbacks: {
                    // use label callback to return the desired label
                    label: function(tooltipItem, data) {
                        return ' '+tooltipItem.xLabel;
                    },
                    // remove title
                    title: function(tooltipItem, data) {}
                }
            }
        };
    </script>
{% endblock %}

{% block body %}

        <main role="main" class="col-xl-12">
        <div class="clearfix">
            <div class="float-left">
                <h1>{{ board.name }}</h1>
                <input type="hidden" id="boardId" value="{{ board.id }}">
            </div>
            {% if board.canUserManage or board.isShareEnabled %}
                <button class="nobtn mt-3 pointer float-right" type="button" data-toggle="modal"
                        data-target="#modalShareBoard">
                    <i class="fas fa-2x fa-share"></i>
                </button>
                {{ include('dashboard/board-share.html.twig') }}
            {% endif %}
        </div>
        <div class="card-deck">
            {% for issue in board.issues %}
                {% if issue.canUserRead %}
                    <div class="col-4 p-0 m-0 mb-4">
                        <div class="card" id="issue-{{ issue.pageId }}">
                            {{ include('dashboard/issue-card.html.twig', { 'issue': issue}) }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            {% if board.canUserWrite %}
                <div class="col-4 h-100 p-0">
                    <div class="card border-dark px-1 pb-1 h-25" >
                        <div class="card-body">
                            <input type="text" placeholder="New issue name" class="pointer borderless w-100 form-control"
                                   id="dashboardIssueName">
                            <div class="mt-3" id="dashboardIssueButtons" style="display: none">
                                <button class="btn btn-success" id="dashboardIssueCreateBtn">Create</button>
                                <button type="button" class="close float-right gaugeCloseBtn mt-1" aria-label="Close"
                                        id="dashboardIssueNameClose">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <input type="hidden" id="dashboardId" value="{{ board.id }}">
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </main>

{% endblock %}

templates/dashboard/card-archived.html.twig
<div class="col-md-3 p-0 mb-3" id="{{ section }}{{ role.board.pageId }}">
    <div class="card">
        <div class="card-header rounded-0 pb-3" style="background-color: #ddd">
            <h5>
                <a href="./{{ role.board.url }}" class="text-dark">{{ role.board.name }}</a>
            </h5>
            <p class="text-secondary m-0">{{ role.board.archivedTime }}</p>
        </div>
    </div>
</div>

templates/dashboard/card-board.html.twig
<div class="col-md-3 p-0 mb-3" id="{{ section }}{{ role.board.pageId }}">
    <div class="card">
        <div class="card-header rounded-0 pb-3 {{ role.board.background }}">
            <button class="nobtn pointer float-right dashboardFavorite {{ section }}orite"
                    id="{{ section }}btn{{ role.board.pageId }}">
                {% if role.favorite %}
                    <i class="fas fa-star"></i>
                {% else %}
                    <i class="far fa-star"></i>
                {% endif %}
            </button>
        </div>
        <div class="card-body mb-4 pb-2">
            <div class="position-absolute" style="height: 1px">
                <div class="dashboard-userlist">
                    {% for user in role.board.activeUsers %}
                        {{ include('user/user-icon.html.twig', {'user': user, 'size': 'small', 'entity': role.board}) }}
                    {% endfor %}
                </div>
            </div>
            <h5 class="card-title">
                <a href="./{{ role.board.url }}">{{ role.board.name }}</a>
            </h5>
        </div>
    </div>
</div>

templates/dashboard/issue-card.html.twig
<div class="card-header clearfix bg-white pr-1">
    <h5 class="float-left text-dark mt-1"><a href="../../{{ issue.url }}"> {{ issue.name }} </a></h5>
    <div class="dropdown float-right">
        <button type="button" class="nobtn float-right text-dark mt-1 pointer"
                id="dropdownCard{{ issue.link }}"
                data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
            <i class="fas fa-ellipsis-v text-dark mx-2"></i>
        </button>
        {% if issue.isShareEnabled or issue.canUserManage %}
            <div class="dropdown-menu my-dropdown dropdown-menu-right" aria-labelledby="dropdownCard{{ issue.link }}">
                {% if issue.isShareEnabled or issue.canUserManage %}
                    <button class="dropdown-item pointer issueShare nobtn px-3 py-1" name="{{ issue.link }}"
                            data-toggle="modal" data-target="#modal{{ issue.link }}">Share</button>
                {% endif %}
                {% if issue.canUserManage %}
                    <button class="dropdown-item pointer issueDelete nobtn px-3 py-1" name="{{ issue.PageId }}">
                        Delete issue</button>
                {% endif %}
            </div>
            {{ include('dashboard/issue-share.html.twig', {'issue': issue}) }}
        {% endif %}
    </div>
    <div class="float-right">
        {% for user in issue.activeUsers %}
            {{ include('user/user-icon.html.twig', {'user': user, 'size': 'small'}) }}
        {% endfor %}
    </div>
</div>
<div class="bg-light card-img-top">
    {{ include('graphs/graph.html.twig', { 'gauges': issue.gauges,
        'gauge_name': issue.link,
        'issue_id': issue.id}) }}
</div>

<div class="card-body">
    {% if issue.countGaugeComments > 0 %}
        <div class="text-smallcaps text-center">
            <a href="../../{{ issue.url }}">Show all {{ issue.countGaugeComments }} changes <i class="fas
            fa-angle-down"></i></a>
        </div>
        {% for comment in issue.latestGaugeComments %}
            <b>{{ comment.user.username }}</b>:
            {{ comment.gauge.name }}&nbsp;{{ comment.oldvalue }}&nbsp;<i class="fas fa-angle-right"></i>&nbsp;<b>{{
            comment.value }}</b>&nbsp;%<br>
        {% endfor %}
    {% endif %}
</div>

templates/dashboard/issue-share.html.twig
<div class="modal fade modalShareIssue" id="modal{{ issue.link }}" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <input type="hidden" id="modal{{ issue.link }}id" value="{{ issue.id }}">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLongTitle">Share {{ issue.name }}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="modal{{ issue.link }}PrimarySection">
                    <div class="clearfix">
                        <div class="d-flex justify-content-between">
                            <h5>Share issue via link</h5>
                            {% if issue.canUserManage %}
                                <div class="dropdown">
                                    <button type="button" class="nobtn float-right text-dark mt-1 pointer"
                                            id="modal{{ issue.link }}Options"
                                            data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
                                        <i class="fas fa-ellipsis-h text-dark mx-2"></i>
                                    </button>
                                    <div class="dropdown-menu my-dropdown dropdown-menu-right mt-1"
                                         aria-labelledby="modal{{ issue.link }}Options">
                                        <a class="dropdown-item pointer" id="modal{{ issue.link }}Disable">Disable link</a>
                                    </div>
                                </div>
                            {% else %}
                                <i class="fas fa-spinner fa-spin" id="modal{{ issue.link }}Options" style="display: none"></i>
                            {% endif %}
                        </div>
                        <div id="modal{{ issue.link }}EnabledSection"
                             style="display: {% if issue.isShareEnabled %} block {% else %} none {% endif %}">
                            <div class="form-group">
                                <label for="modal{{ issue.link }}Link" title="Link to share this project" class="w-100">
                                    <input type="text" id="modal{{ issue.link }}Link" class="form-control bg-white"
                                           readonly="readonly" data-toggle="tooltip" data-placement="top"
                                           title="Link copied to clipboard"
                                           value="{{ app.request.httphost }}/{{ issue.url }}?{{ issue.shareLink }}">
                                </label>
                                <div class="input-group">
                                    {#{{ constant('ROLE_READ', board) }}#}
                                    {% if issue.canUserManage %}
                                        <select  class="form-control" id="modal{{ issue.link }}Select"
                                                 title="Choose the rights for users with this link">
                                            <option value="{{ constant('ROLE_WRITE', issue) }}"
                                                {% if (issue.shareRights == constant('ROLE_WRITE', issue) or
                                                issue.shareRights == constant('ROLE_ANON', issue)) %}selected{% endif %}>
                                                Anyone with the link can edit</option>
                                            <option value="{{ constant('ROLE_READ', issue) }}"
                                                {% if issue.shareRights == constant('ROLE_READ', issue) %}selected{% endif %}>
                                                Anyone with the link can view</option>
                                        </select>
                                    {% else %}
                                        <input type="text" class="form-control bg-white" disabled
                                               value="{% if issue.shareRights is constant('ROLE_READ', issue)
                                               %}Anyone with the link can view{% else %}Anyone with the link can edit{% endif %}">
                                    {% endif %}
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-secondary"
                                                id="modal{{ issue.link }}CopyBtn">
                                            Copy to clipboard</button>
                                    </div>
                                </div>
                            </div>

                            {% if issue.canUserManage %}
                                <label for="modal{{ issue.link }}Anonymous"
                                       title="Choose to allow editing tasks in this project to anonymous
                                     or only logged in users">
                                    <input type="checkbox" id="modal{{ issue.link }}Anonymous"
                                            {% if issue.shareRights == constant('ROLE_READ', issue) %} disabled
                                    {% elseif issue.shareRights == constant('ROLE_ANON', issue) %}checked="checked" {%
                                    endif %}>
                                    <span id="modal{{ issue.link }}AnonymousText">
                                        Allow anonymous users to edit this project too</span>
                                </label>
                            {% endif %}
                        </div>
                        <div id="modal{{ issue.link }}DisabledSection" style="display: {% if not issue.isShareEnabled %} block {% else %} none {% endif %}">
                            <div class="d-flex justify-content-center">
                                <button class="btn btn-success" id="modal{{ issue.link }}Enable">Enabled link sharing</button>
                            </div>
                        </div>
                    </div>
                    {% if issue.canUserManage %}
                        <hr>
                        <div>
                            <div class="d-flex justify-content-between">
                                <h5>Invite people</h5>
                                <i class="fas fa-spinner fa-spin" id="modal{{ issue.link }}InviteLoading" style="display:
                                none"></i>
                            </div>
                            <div class="input-group">
                                <input type="text" placeholder="Enter name or email address" class="form-control"
                                       data-toggle="tooltip" data-placement="top" title="Email with invitation was send"
                                       id="modal{{ issue.link }}AddUser">
                                <select class="custom-select" id="modal{{ issue.link }}InviteRole">
                                    <option value="{{ constant('ROLE_WRITE', issue) }}">Can edit</option>
                                    <option value="{{ constant('ROLE_READ', issue) }}">Can view</option>
                                </select>
                            </div>
                            <button class="btn btn-success mt-1" id="modal{{ issue.link }}InviteBtn" style="display:none;">Invite</button>
                        </div>
                    {% endif %}
                </div>
                {% if issue.canUserManage %}
                    <div id="modal{{ issue.link }}IndividualSection" style="display: none">
                        <div class="d-flex justify-content-between">
                            <h5>Who has access</h5>
                            <i class="fas fa-spinner fa-spin" id="modal{{ issue.link }}IndividualLoading"
                               style="display: none"></i>
                        </div>
                        <span class="text-secondary">List of all users with rights to this issue.</span>
                        <table class="table mt-2">
                            <tbody id="modal{{ issue.link }}Userlist">
                            {#{{ include('dashboard/share-userlist.html.twig', {'users': issue.allUsers}) }}#}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
                <div class="d-flex justify-content-between mt-5">
                    <button class="btn btn-primary float-left" data-dismiss="modal" >Done</button>
                    {% if issue.canUserManage %}
                        <button class="nobtn float-right text-secondary pointer"
                                id="modal{{ issue.link }}Individual">Manage individual users</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/share-userlist.html.twig
{% for role in users %}
    <tr>
        <td>{{ include('user/user-icon.html.twig', {'user': role.user, 'size': 'small'}) }}</td>
        <td><span class="userName {% if role.isActive != 1 %}text-secondary{% endif %}"
                  id="modalBoardShareUser{{ role.user.uniquelink }}">{{ role.user.username }}</span></td>
        <td>
            {% if role.rights is constant('App\\Entity\\Board::ROLE_ADMIN') %}
                <span class="text-secondary">Is owner</span>
            {% else %}
                {{ role.user.uniquelink }}
                <select class="custom-select userChange" name="{{ role.user.uniquelink }}">
                    <option value="{{ constant('App\\Entity\\Board::ROLE_WRITE') }}"
                            {% if (role.rights is constant('App\\Entity\\Board::ROLE_ANON') or
                                (role.rights is constant('App\\Entity\\Board::ROLE_WRITE') and role.user.isAnonymous != 1))
                            and (role.isBoardHistory != 1 or role.isShareEnabled == 1)
                            %}selected{% endif %}>
                        Can edit</option>
                    <option value="{{ constant('App\\Entity\\Board::ROLE_READ') }}"
                            {% if (role.rights is constant('App\\Entity\\Board::ROLE_READ') or
                            (role.rights is constant('App\\Entity\\Board::ROLE_WRITE') and role.user.isAnonymous == 1))
                            and (role.isBoardHistory != 1 or role.isShareEnabled == 1) %}selected{% endif %}>
                        Can view</option>
                    <option value="{{ constant('App\\Entity\\Board::ROLE_VOID') }}"
                            {% if role.isActive != 1 or (role.isShareEnabled != 1 and role.isBoardHistory == 1)
                            %}selected{%
                    endif %}>
                        Cannot view</option>
                </select>
            {% endif %}
        </td>
        <td>
            {% if role.rights is not constant('App\\Entity\\Board::ROLE_ADMIN') %}
                <button class="nobtn pointer userRemove"  data-toggle="tooltip"
                        data-placement="top" title="Remove {{ role.user.username }}"
                        name="{{ role.user.uniquelink }}">
                    <i class="fas fa-times"></i></button>
            {% endif %}
        </td>
    </tr>
{% endfor %}